"""Rename filename to original_name in File

Revision ID: 446631ab48b0
Revises: e1dd3dbd7ab6
Create Date: 2026-07-09 18:55:48.019060

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '446631ab48b0'
down_revision = 'e1dd3dbd7ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_name', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('yandexdisk_path', sa.String(length=512), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('yandexdisk_path')
        batch_op.drop_column('original_name')

    # ### end Alembic commands ###
